name: Github Pagesへのデプロイ

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3
      - name: Github Pagesをセットアップ
        uses: actions/checkout@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: インストール
        run: npm install
      - name: ビルド
        run: npm run build
      - name: アップロード
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_book/'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: デプロイ
        id: deployment
        uses: actions/deploy-pages@v2
